### ISSUE TITLE
Possibility of adding lang files.

### ISSUE THREAD

**Issue by K0-RR** [Blobanium/Loading-Timer#15]
I would like to translate the toast to the Polish but it seems it's not possible.

**Comment by Blobanium** [comment]
I'll probably look into it, but as of rn (or at the time I am writing this for those of you time travelers) im currently far away from my pc (and I dont have a laptop that can run VSC(my coding app) and minecraft sadly) because I'm outside of my hometown so it probably won't be for a couple of days until I can get back to coding again.. so yeah.... However I wound be happy to merge pull requests for this topic for the time being

**Comment by Blobanium** [comment]
So i managed to add the lang implementation. However, as for right now i only implemented it for toast notifs, idk how im going to translate log messages, most likely not possible, but if there is a way ill try.

Anyways closing this for now since the base lang structure(or something else in those lines) has been implemented
